"""Модуль-шлюз для Telegram-бота (aiogram).

Никакой бизнес-логики — только транспортный слой.
Входящие сообщения → шина, исходящие → aiogram.
"""

from src.modules.job_bot.texts import (
    CONFIRM_BUTTON_NO,
    CONFIRM_BUTTON_YES,
    MAIN_MENU_BUTTON_FIND_JOB,
    MAIN_MENU_BUTTON_MY_SUBSCRIPTIONS,
    MAIN_MENU_BUTTON_SETTINGS,
    MAIN_MENU_PLACEHOLDER,
    OFFER_BUTTON_DETAILS,
    OFFER_BUTTON_SUBSCRIBE_SIMILAR,
    SUBSCRIPTION_BUTTON_EDIT,
    SUBSCRIPTION_BUTTON_UNSUBSCRIBE,
    VACANCY_LOCATION_TEMPLATE,
    VACANCY_SALARY_TEMPLATE,
    VACANCY_SALARY_UNKNOWN,
    VACANCY_TAGS_TEMPLATE,
    WELCOME_MESSAGE,
)

__all__ = [
    # Тексты
    "WELCOME_MESSAGE",
    "MAIN_MENU_BUTTON_FIND_JOB",
    "MAIN_MENU_BUTTON_MY_SUBSCRIPTIONS",
    "MAIN_MENU_BUTTON_SETTINGS",
    "MAIN_MENU_PLACEHOLDER",
    "SUBSCRIPTION_BUTTON_EDIT",
    "SUBSCRIPTION_BUTTON_UNSUBSCRIBE",
    "OFFER_BUTTON_DETAILS",
    "OFFER_BUTTON_SUBSCRIBE_SIMILAR",
    "CONFIRM_BUTTON_YES",
    "CONFIRM_BUTTON_NO",
    "VACANCY_SALARY_TEMPLATE",
    "VACANCY_LOCATION_TEMPLATE",
    "VACANCY_TAGS_TEMPLATE",
    "VACANCY_SALARY_UNKNOWN",
]

