"""Add telegram_settings table

Revision ID: abc123telegram_settings
Revises: 173743107479
Create Date: 2026-07-02

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc123telegram_settings'
down_revision: Union[str, None] = '173743107479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_settings',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('read_groups', sa.Boolean(), nullable=False, default=True),
    sa.Column('read_personal', sa.Boolean(), nullable=False, default=True),
    sa.Column('read_channels', sa.Boolean(), nullable=False, default=True),
    sa.Column('whitelist_chat_ids', sa.JSON(), nullable=True, default=list),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_settings_account_id'), 'telegram_settings', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_settings_account_id'), table_name='telegram_settings')
    op.drop_table('telegram_settings')
    # ### end Alembic commands ###
